### ISSUE TITLE
Documentation in Readme

### ISSUE THREAD

**Issue by strarsis** [Log1x/blade-svg-sage#1]
More documentation for this README would be great - 
e,g, how to actually place a SVG in a blade document.

**Comment by Log1x** [comment]
As this is a fork of the original blade-svg, all of the documentation other than configuration differences (which I included in blade-svg-sage's README) should be 1:1 to the documentation provided [here](https://github.com/adamwathan/blade-svg/blob/master/readme.md).

It does appear he renamed `@icon()` to `@svg()`-- I will push an update to catch up to his branch shortly.
