### ISSUE TITLE
Inline markup?

### ISSUE THREAD

**Issue by strarsis** [Log1x/blade-svg-sage#10]
Is it possible to inject extra SVG/HTML markup into the SVG to be inlined?
This would allow to add text and other dynamically generated markup and 
let the SVG handle the effect / adjust its dimensions to it.

**Comment by strarsis** [comment]
@Log1x: Are there any plans for this in near future?

**Comment by Log1x** [comment]
Enable with:

```
add_filter('bladesvg_inline', function () {
    return true;
});
```

and use the docs seen [here](https://github.com/adamwathan/blade-svg/blob/master/readme.md) to inject classes, ID's, etc.
