### ISSUE TITLE
Doesn't work as mu-plugin in theme

### ISSUE THREAD

**Issue by strarsis** [Log1x/blade-svg-sage#2]
I required this (mu-)plugin in a sage theme - but this plugin isn't 
listed as obligatory installed/enabled plugin.

It works if I require it for the site instead for the theme (site/) - 
but it should work for the theme.

**Comment by Log1x** [comment]
You need to specify the installer-paths in your theme's composer.json -- Sage 9 by default doesn't have them.

```
"extra": {
  "installer-paths": {
    "../../mu-plugins/{$name}/": ["type:wordpress-muplugin"],
    "../../plugins/{$name}/": ["type:wordpress-plugin"]
  }
},
```

A sane spot for it would be right above `"scripts"`.
