### ISSUE TITLE
Package nothingworks/blade-svg is abandoned

### ISSUE THREAD

**Issue by designlobby** [Log1x/blade-svg-sage#23]
Hi there, when installing blade-svg-sage on Sage 9.0.9 I am getting the message:

Package nothingworks/blade-svg is abandoned, you should avoid using it. Use blade-ui-kit/blade-icons instead.

Is blade-svg-sage still safe to use?

Many thanks,
Gareth

**Comment by Log1x** [comment]
yeah you shouldn't have any issues. despite it being abandoned the underlying code is quite simple and shouldn't need changed anytime soon (if ever)

**Comment by designlobby** [comment]
Great, thanks Brandon!
