### ISSUE TITLE
Call to undefined function app()

### ISSUE THREAD

**Issue by strarsis** [Log1x/blade-svg-sage#3]
I required 'nothingworks/blade-svg' using composer - I get an error message when loading the page:
````
[...]
FatalThrowableError: Call to undefined function app() in /srv/www/vendor/nothingworks/blade-svg/src/helpers.php:25 [...]
````
I installed blade-svg for the site (Bedrock project), so the extra config in composer.json was already in place.

**Comment by Log1x** [comment]
You required the wrong repository. This is merely a fork of blade-svg to be compatible with Sage's implementation of Blade, at least until we are able to register service containers; in which case this will become deprecated.

**Comment by strarsis** [comment]
Thanks, I required 'log1x/blade-svg-sage' with `composer require log1x/blade-svg-sage` now.
