### ISSUE TITLE
Path issues after update

### ISSUE THREAD

**Issue by strarsis** [Log1x/blade-svg-sage#6]
This may be related to https://github.com/Log1x/blade-svg-sage/issues/5.

After updating blade-svg-sage to latest (using composer), the file isn't found anymore:
`/dist/images/svg/icons not found.`

Do I have to adjust the code?

**Comment by Log1x** [comment]
The path was changed to be 1:1 with the original `blade-svg`.

You can use the following filter to change it:

```
add_filter('bladesvg_image_path', function () {
    return parse_asset_path('images/svg/icons');
});
```

**Comment by strarsis** [comment]
@Log1x:
The 'bladesvg_image_path' filter doesn't seem to work.

```php
add_filter('bladesvg_image_path', function () {
    return parse_asset_path('images/icons');
});
````

parse_asset_path returns '/dist/images/svg/icons' instead the filtered '/dist/images/icons'.

```php
    function parse_asset_path($asset)
    {
        [...]
        return trailingslashit(\App\config('theme')['dir']) . trailingslashit('dist') . \App\sage('assets')->get($asset);
    }
````
