### ISSUE TITLE
Call to undefined function app()

### ISSUE THREAD

**Issue by strarsis** [Log1x/blade-svg-sage#9]
I required latest blade-svg-sage as theme composer package dependency.
However, I get an error on the pages where `@icon` is used:
````
Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined function app() in /srv/www/web/app/themes/the-theme/vendor/nothingworks/blade-svg/src/helpers.php on line 15
````
How can I help with/further debug this?

**Comment by Log1x** [comment]
Hmm, you sure you're on dev-master? It should be doing `\BladeSvgSage\svg_image()` when doing `@icon`, not `App\svg_image()`.

**Comment by strarsis** [comment]
@Log1x: I switched to 'dev-master' and ran `composer update` but still the same error occurs.

**Comment by strarsis** [comment]
@Log1x: How can I further debug / help with this?
Currently I either have the bug with missing image in production build - or the fatal error.

**Comment by strarsis** [comment]
@Log1x: On a fresh theme the fatal error went away. 
However, the SVG cannot be found, the hash is not resolved.

Composer:
```json
"log1x/blade-svg-sage": "1.0.5"
````

I cannot find any code in latest `log1x/blade-svg-sage` (1.0.5) that resolves 
the file name to a hashed file name for production.

**Comment by strarsis** [comment]
@Log1x: Any news on this?

**Comment by strarsis** [comment]
@Log1x: Can I help fixing this issue?

**Comment by strarsis** [comment]
This seems to work now.
